"""summary.md rendering from the SQLite store.

Formal results are grouped by (protocol identity, sample manifest identity) so
different evaluation conditions are never silently mixed.  Smoke runs, partial
runs and unverified runs are diagnostics only unless explicitly included.
"""

from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path

from . import __version__ as TOOL_VERSION
from .util import digest, now_iso

TOP_CATEGORY_KEY = digest([])


def _format_score(score, display_kind, unit):
    if score is None:
        return 'N/A'
    try:
        value = float(score)
    except (TypeError, ValueError):
        return 'N/A'
    if display_kind == 'percent' or unit == '%':
        return f'{value * 100:.1f}%'
    if unit:
        return f'{value:.4f} {unit}'
    return f'{value:.4f}'


def _short(value, length=10):
    return (value or '')[:length]


def collect_formal_rows(store, *, include_partial: bool):
    accepted = ['complete'] if not include_partial else ['complete', 'partial']
    placeholders = ', '.join('?' for _ in accepted)
    rows = store.conn.execute(
        f"""
        SELECT r.*, m.metric_name, m.aggregation, m.dimensions_json, m.score, m.macro_score,
               m.display_kind, m.unit, m.direction, m.num AS metric_num, m.is_primary
        FROM runs r JOIN metrics m
          ON m.run_id = r.run_id AND m.is_primary = 1 AND m.category_key = ? AND m.subset = ''
        WHERE r.validity_status IN ({placeholders})
          AND r.comparability = 'verified'
          AND r.profile != 'smoke'
        ORDER BY r.finished_at
        """,
        [TOP_CATEGORY_KEY, *accepted],
    ).fetchall()
    return rows


def collect_other_rows(store):
    """Everything not eligible for the formal comparison table."""
    rows = store.conn.execute(
        """
        SELECT r.*, m.metric_name, m.score, m.num AS metric_num, m.display_kind, m.unit, m.is_primary
        FROM runs r LEFT JOIN metrics m
          ON m.run_id = r.run_id AND m.is_primary = 1 AND m.category_key = ? AND m.subset = ''
        WHERE r.validity_status IS NULL OR r.validity_status != 'complete'
           OR r.comparability != 'verified'
           OR r.profile = 'smoke'
           OR m.metric_name IS NULL
        ORDER BY r.started_at DESC
        LIMIT 200
        """,
        [TOP_CATEGORY_KEY],
    ).fetchall()
    return rows


def _latest_per_model_dataset(rows):
    latest = {}
    for row in rows:
        key = (row['protocol_identity'] or 'unknown', row['sample_manifest_identity'] or 'unknown',
               row['model_config_identity'] or row['model_alias'], row['dataset'],
               row['metric_name'], row['aggregation'] or '', row['dimensions_json'] or '{}')
        current = latest.get(key)
        if current is None or (row['finished_at'] or '') >= (current['finished_at'] or ''):
            latest[key] = row
    return list(latest.values())


def _group_key(row):
    return (row['protocol_identity'] or 'unknown', row['sample_manifest_identity'] or 'unknown')


def render(store, data_root: Path, *, include_partial: bool = False) -> str:
    lines = [
        '# LLM Benchmark Summary',
        '',
        f'Generated by llmbench {TOOL_VERSION} at {now_iso()}  ',
        f'Data root: `{data_root}`  ',
        'Tool version is the renderer; each run keeps the EvalScope version it actually used.',
        '',
    ]
    formal_rows = _latest_per_model_dataset(collect_formal_rows(store, include_partial=include_partial))
    groups = defaultdict(list)
    for row in formal_rows:
        groups[_group_key(row)].append(row)

    lines += ['## Formal results (comparable groups)', '']
    if not groups:
        lines += ['_No complete, content-verified non-smoke runs yet._', '']
    for (protocol, samples), rows in sorted(groups.items()):
        rows.sort(key=lambda row: (row['dataset'], row['model_alias']))
        sample_count = ', '.join(
            f"{row['dataset']}={row['metric_num']}" for row in rows
        )
        lines += [
            f'### protocol `{_short(protocol)}` / samples `{_short(samples)}`',
            '',
            f'Sample sizes: {sample_count}',
            '',
            '| Model | Model config | Dataset | Metric | Score | Num | Profile | Validity | Finished | Run | EvalScope |',
            '|---|---|---|---|---:|---:|---|---|---|---|---|',
        ]
        for row in rows:
            lines.append(
                f"| {row['model_alias']} | `{_short(row['model_config_identity'])}` "
                f"| {row['dataset']} | {row['metric_name']} "
                f"| {_format_score(row['score'], row['display_kind'], row['unit'])} "
                f"| {row['metric_num']} | {row['profile']} | {row['validity_status']} "
                f"| {row['finished_at']} | `{row['run_id']}` | {row['evalscope_version']} |"
            )
        lines.append('')

    lines += ['## Diagnostics', '']
    lines += ['### Smoke / partial / unverified runs', '',
              '| Run | Model | Dataset | Exec | Validity | Comparability | Reason | Score | Finished | EvalScope |',
              '|---|---|---|---|---|---|---|---:|---|---|']
    diagnostics_rows = []
    for row in collect_other_rows(store):
        label = 'diagnostic' if row['profile'] == 'smoke' else row['profile']
        score = _format_score(row['score'], row['display_kind'], row['unit']) if row['metric_name'] else 'N/A'
        reason = (row['status_reason'] or '')[:140].replace('|', '\\|').replace('\n', ' ').replace('\r', ' ')
        lines.append(
            f"| `{row['run_id']}` | {row['model_alias']} | {row['dataset']} ({label}) "
            f"| {row['execution_status']} | {row['validity_status']} | {row['comparability']} "
            f"| {reason} | {score} | {row['finished_at']} | {row['evalscope_version']} |"
        )
        diagnostics_rows.append(row)
    if not diagnostics_rows:
        lines.append('| _none_ | | | | | | | | | |')
    lines.append('')

    truncation = []
    for row in store.conn.execute(
        """SELECT run_id, dataset, diagnostics_json FROM runs
           WHERE diagnostics_json IS NOT NULL ORDER BY started_at DESC LIMIT 100"""
    ):
        try:
            diagnostics = json.loads(row['diagnostics_json'])
        except json.JSONDecodeError:
            continue
        if not diagnostics.get('generation_calls'):
            continue
        truncation.append((row, diagnostics))
    if truncation:
        lines += ['### Generation diagnostics (per run)', '',
                  '| Run | Dataset | Gen calls | Truncated | Content filter | Unknown stop | Missing stop | Missing usage | Agent steps (max) | Tokens in/out |',
                  '|---|---|---:|---:|---:|---:|---:|---:|---:|---|']
        for row, diagnostics in truncation:
            usage = diagnostics.get('usage_totals') or {}
            steps = diagnostics.get('agent_steps') or {}
            lines.append(
                f"| `{row['run_id']}` | {row['dataset']} | {diagnostics.get('generation_calls', 0)} "
                f"| {diagnostics.get('truncated_calls', 0)} | {diagnostics.get('content_filter_calls', 0)} "
                f"| {diagnostics.get('unknown_stop_reason_calls', 0)} "
                f"| {diagnostics.get('samples_without_stop_reason', 0)} "
                f"| {diagnostics.get('samples_without_usage', 0)} "
                f"| {steps.get('max', 'unknown')} "
                f"| {int(usage.get('input_tokens', 0))}/{int(usage.get('output_tokens', 0))} |"
            )
        lines.append('')

    lines += [
        '## Interpretation notes',
        '',
        '- `complete` + `verified` is the only combination used for the formal table;',
        '  `partial`, `invalid`, `unverified` and `legacy` runs are diagnostics.',
        '- Runs are grouped by protocol identity and sample manifest identity; groups with',
        '  different hashes must not be compared directly.',
        '- A low score from a valid run is a model result, not an infrastructure failure.',
        '- Truncation/diagnostics are reported, never folded into the benchmark score.',
        '',
    ]
    return '\n'.join(lines)


def write(store, out_path: Path, data_root: Path, *, include_partial: bool = False) -> Path:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(render(store, data_root, include_partial=include_partial), encoding='utf-8')
    return out_path
